BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=true';
    BEGIN
       EXECUTE IMMEDIATE 'CREATE USER jerryuser IDENTIFIED BY Password12';
    EXCEPTION
       WHEN OTHERS THEN
          NULL;
    END;
    EXECUTE IMMEDIATE 'GRANT CONNECT TO jerryuser';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO jerryuser';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO jerryuser';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO jerryuser';
END;